require("dotenv").config();
require("../services/mongo");

const DataPoint = require("../models/datapoint");

// Sample data for French elections
const sampleData = [
  // 2022 Presidential Election - First Round
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Emmanuel Macron",
    party: "LREM",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 27.85,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Marine Le Pen",
    party: "RN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 23.15,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Jean-Luc Mélenchon",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 21.95,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Éric Zemmour",
    party: "RECONQUETE",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 7.07,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Valérie Pécresse",
    party: "LR",
    nuance: "Droite",
    level: "national",
    city: "",
    value: 4.78,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Yannick Jadot",
    party: "EELV",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 4.63,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Jean Lassalle",
    party: "RES",
    nuance: "Autre",
    level: "national",
    city: "",
    value: 3.13,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Fabien Roussel",
    party: "PCF",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 2.28,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-10"),
    candidate_name: "Anne Hidalgo",
    party: "PS",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 1.75,
    poll_source: null,
  },

  // Polls before 2022 Presidential Election
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-01"),
    candidate_name: "Emmanuel Macron",
    party: "LREM",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 26.5,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-01"),
    candidate_name: "Marine Le Pen",
    party: "RN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 24.0,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-01"),
    candidate_name: "Jean-Luc Mélenchon",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 19.5,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-01"),
    candidate_name: "Éric Zemmour",
    party: "RECONQUETE",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 8.5,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-01"),
    candidate_name: "Valérie Pécresse",
    party: "LR",
    nuance: "Droite",
    level: "national",
    city: "",
    value: 9.0,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-04-01"),
    candidate_name: "Yannick Jadot",
    party: "EELV",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 5.5,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-15"),
    candidate_name: "Emmanuel Macron",
    party: "LREM",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 28.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-15"),
    candidate_name: "Marine Le Pen",
    party: "RN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 22.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-15"),
    candidate_name: "Jean-Luc Mélenchon",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 17.5,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-15"),
    candidate_name: "Éric Zemmour",
    party: "RECONQUETE",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 10.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-15"),
    candidate_name: "Valérie Pécresse",
    party: "LR",
    nuance: "Droite",
    level: "national",
    city: "",
    value: 12.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-15"),
    candidate_name: "Yannick Jadot",
    party: "EELV",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 6.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-01"),
    candidate_name: "Emmanuel Macron",
    party: "LREM",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 27.0,
    poll_source: "ELABE",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-01"),
    candidate_name: "Marine Le Pen",
    party: "RN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 18.0,
    poll_source: "ELABE",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-01"),
    candidate_name: "Jean-Luc Mélenchon",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 14.5,
    poll_source: "ELABE",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-01"),
    candidate_name: "Éric Zemmour",
    party: "RECONQUETE",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 13.0,
    poll_source: "ELABE",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-03-01"),
    candidate_name: "Valérie Pécresse",
    party: "LR",
    nuance: "Droite",
    level: "national",
    city: "",
    value: 13.5,
    poll_source: "ELABE",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-02-15"),
    candidate_name: "Emmanuel Macron",
    party: "LREM",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 25.0,
    poll_source: "HARRIS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-02-15"),
    candidate_name: "Marine Le Pen",
    party: "RN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 17.0,
    poll_source: "HARRIS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-02-15"),
    candidate_name: "Éric Zemmour",
    party: "RECONQUETE",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 14.0,
    poll_source: "HARRIS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-02-15"),
    candidate_name: "Valérie Pécresse",
    party: "LR",
    nuance: "Droite",
    level: "national",
    city: "",
    value: 16.0,
    poll_source: "HARRIS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2022-t1",
    election_type: "presidentielle",
    date: new Date("2022-02-15"),
    candidate_name: "Jean-Luc Mélenchon",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 12.0,
    poll_source: "HARRIS",
  },

  // Polls before 2017 Presidential Election
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-15"),
    candidate_name: "Emmanuel Macron",
    party: "EM",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 23.5,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-15"),
    candidate_name: "Marine Le Pen",
    party: "FN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 23.0,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-15"),
    candidate_name: "François Fillon",
    party: "LR",
    nuance: "Droite",
    level: "national",
    city: "",
    value: 19.5,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-15"),
    candidate_name: "Jean-Luc Mélenchon",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 19.0,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-15"),
    candidate_name: "Benoît Hamon",
    party: "PS",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 7.5,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-01"),
    candidate_name: "Emmanuel Macron",
    party: "EM",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 24.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-01"),
    candidate_name: "Marine Le Pen",
    party: "FN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 24.5,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-01"),
    candidate_name: "François Fillon",
    party: "LR",
    nuance: "Droite",
    level: "national",
    city: "",
    value: 19.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-01"),
    candidate_name: "Jean-Luc Mélenchon",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 18.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-01"),
    candidate_name: "Benoît Hamon",
    party: "PS",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 8.0,
    poll_source: "IPSOS",
  },

  // Polls before 2024 European Elections
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-01"),
    candidate_name: "Jordan Bardella",
    party: "RN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 32.0,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-01"),
    candidate_name: "Raphaël Glucksmann",
    party: "PS",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 14.0,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-01"),
    candidate_name: "Valérie Hayer",
    party: "RENAISSANCE",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 15.5,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-01"),
    candidate_name: "Manon Aubry",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 10.0,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-01"),
    candidate_name: "Marie Toussaint",
    party: "EELV",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 6.0,
    poll_source: "IFOP",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-05-15"),
    candidate_name: "Jordan Bardella",
    party: "RN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 30.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-05-15"),
    candidate_name: "Raphaël Glucksmann",
    party: "PS",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 13.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-05-15"),
    candidate_name: "Valérie Hayer",
    party: "RENAISSANCE",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 16.0,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-05-15"),
    candidate_name: "Manon Aubry",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 9.5,
    poll_source: "IPSOS",
  },
  {
    type: "poll",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-05-15"),
    candidate_name: "Marie Toussaint",
    party: "EELV",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 5.5,
    poll_source: "IPSOS",
  },

  // 2017 Presidential Election - First Round
  {
    type: "result",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-23"),
    candidate_name: "Emmanuel Macron",
    party: "EM",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 24.01,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-23"),
    candidate_name: "Marine Le Pen",
    party: "FN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 21.3,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-23"),
    candidate_name: "François Fillon",
    party: "LR",
    nuance: "Droite",
    level: "national",
    city: "",
    value: 20.01,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-23"),
    candidate_name: "Jean-Luc Mélenchon",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 19.58,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "presidentielle-2017-t1",
    election_type: "presidentielle",
    date: new Date("2017-04-23"),
    candidate_name: "Benoît Hamon",
    party: "PS",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 6.36,
    poll_source: null,
  },

  // 2024 European Elections
  {
    type: "result",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-09"),
    candidate_name: "Jordan Bardella",
    party: "RN",
    nuance: "Extreme droite",
    level: "national",
    city: "",
    value: 31.37,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-09"),
    candidate_name: "Raphaël Glucksmann",
    party: "PS",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 13.83,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-09"),
    candidate_name: "Valérie Hayer",
    party: "RENAISSANCE",
    nuance: "Centre",
    level: "national",
    city: "",
    value: 14.6,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-09"),
    candidate_name: "Manon Aubry",
    party: "LFI",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 9.89,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "europeennes-2024",
    election_type: "europeenne",
    date: new Date("2024-06-09"),
    candidate_name: "Marie Toussaint",
    party: "EELV",
    nuance: "Gauche",
    level: "national",
    city: "",
    value: 5.5,
    poll_source: null,
  },

  // Paris Municipal Elections 2020
  {
    type: "result",
    election_id: "municipales-2020-paris",
    election_type: "municipale",
    date: new Date("2020-06-28"),
    candidate_name: "Anne Hidalgo",
    party: "PS",
    nuance: "Gauche",
    level: "municipal",
    city: "Paris",
    value: 48.5,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "municipales-2020-paris",
    election_type: "municipale",
    date: new Date("2020-06-28"),
    candidate_name: "Rachida Dati",
    party: "LR",
    nuance: "Droite",
    level: "municipal",
    city: "Paris",
    value: 32.3,
    poll_source: null,
  },
  {
    type: "result",
    election_id: "municipales-2020-paris",
    election_type: "municipale",
    date: new Date("2020-06-28"),
    candidate_name: "Agnès Buzyn",
    party: "LREM",
    nuance: "Centre",
    level: "municipal",
    city: "Paris",
    value: 13.7,
    poll_source: null,
  },
];

async function seedDatabase() {
  try {
    console.log("Starting database seed...");

    // Clear existing data
    await DataPoint.deleteMany({});
    console.log("Cleared existing data points");

    // Insert sample data
    const inserted = await DataPoint.insertMany(sampleData);
    console.log(`Successfully inserted ${inserted.length} data points`);

    console.log("\nData summary:");
    const resultCount = await DataPoint.countDocuments({ type: "result" });
    const pollCount = await DataPoint.countDocuments({ type: "poll" });
    console.log(`- Results: ${resultCount}`);
    console.log(`- Polls: ${pollCount}`);

    const electionTypes = await DataPoint.distinct("election_type");
    console.log(`- Election types: ${electionTypes.join(", ")}`);

    const levels = await DataPoint.distinct("level");
    console.log(`- Levels: ${levels.join(", ")}`);

    const cities = await DataPoint.distinct("city");
    console.log(`- Cities: ${cities.filter((c) => c).join(", ") || "None"}`);

    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
